name: Run Python Script

on:
  workflow_dispatch:
    inputs:
      year:
        description: 'Year for the script'
        required: true
        default: '2023'
permissions:
  contents: write
jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  

    - name: Run Python script
      run: python scraper.py ${{ github.event.inputs.year }} 
    
    - name: Commit and push changes
      run: |
        git config --global user.email "<>"
        git config --global user.name "github-bot"
        git checkout -b data-${{ github.event.inputs.year }}
        git add .
        git commit -m "Update CSV for year ${{ github.event.inputs.year }} "
        git push origin data-${{ github.event.inputs.year }}
